// Minimal base64 PDF stub (1-page blank PDF) for mock testing
const STUB_PDF_BASE64 =
  'JVBERi0xLjQKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjIgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9LaWRzIFszIDAgUl0KL0NvdW50IDEKPD4KZW5kb2JqCjMgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovTWVkaWFCb3ggWzAgMCA2MTIgNzkyXQovQ29udGVudHMgNCAwIFIKL1Jlc291cmNlcyA8PAovRm9udCA8PAovRjEgNSAwIFIKPj4KPj4KPj4KZW5kb2JqCjQgMCBvYmoKPDwKL0xlbmd0aCA0NAo+PgpzdHJlYW0KQlQKL0YxIDI0IFRmCjEwMCA3MDAgVGQKKFJldmlzZWQgUmVzdW1lKSBUagpFVAplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUxCi9CYXNlRm9udCAvSGVsdmV0aWNhCj4+CmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA1OCAwMDAwMCBuIAowMDAwMDAwMTE1IDAwMDAwIG4gCjAwMDAwMDAyNjYgMDAwMDAgbiAKMDAwMDAwMDM2MCAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9TaXplIDYKL1Jvb3QgMSAwIFIKPj4Kc3RhcnR4cmVmCjQ0MwolJUVPRgo='

const mockData = {
  1: { 
    job_id: 1,
    job_title: 'Senior Frontend Engineer',
    job_url: 'https://example.com/jobs/1',
    company: 'Stripe',
    company_url: 'https://stripe.com',
    location: 'San Francisco, CA (Hybrid)',
    posted_time: '2026-03-30',
    application_url: 'https://stripe.com/jobs/apply/1',
    description:
      'We are looking for a Senior Frontend Engineer to join our Payments team. You will build and scale the interfaces used by millions of businesses worldwide. You\'ll work closely with product and design to craft polished, accessible, and performant web experiences.',
    work_type: 'Full-time',
    sector: 'Fintech',
    technical_skills: ['React', 'TypeScript', 'CSS-in-JS', 'GraphQL', 'Webpack'],
    soft_skills: ['Cross-functional collaboration', 'Mentorship', 'Attention to detail'],
    experience_fit: 88,
    domain_fit: 72,
    overall_score: 82,
    revised_resume: STUB_PDF_BASE64,
  },
  2: {
    job_id: 2,
    job_title: 'Full Stack Engineer',
    job_url: 'https://example.com/jobs/2',
    company: 'Linear',
    company_url: 'https://linear.app',
    location: 'Remote',
    posted_time: '2026-03-28',
    application_url: 'https://linear.app/jobs/apply/2',
    description:
      'Linear is building the next generation of project management tooling. We\'re looking for a full stack engineer passionate about developer experience and product quality. You\'ll own features end-to-end, from backend data modeling to React UI.',
    work_type: 'Full-time',
    sector: 'Productivity / SaaS',
    technical_skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'Redis'],
    soft_skills: ['Ownership mindset', 'Async communication', 'Self-direction'],
    experience_fit: 79,
    domain_fit: 65,
    overall_score: 74,
    revised_resume: STUB_PDF_BASE64,
  },
  3: {
    job_id: 3,
    job_title: 'React Native Engineer',
    job_url: 'https://example.com/jobs/3',
    company: 'Duolingo',
    company_url: 'https://duolingo.com',
    location: 'Pittsburgh, PA (On-site)',
    posted_time: '2026-03-25',
    application_url: 'https://duolingo.com/jobs/apply/3',
    description:
      'Join Duolingo\'s mobile team to build engaging language-learning experiences for 500M+ users. You\'ll work on the React Native codebase, optimize app performance, and ship experiments that drive daily active user growth.',
    work_type: 'Full-time',
    sector: 'EdTech',
    technical_skills: ['React Native', 'JavaScript', 'iOS', 'Android', 'Expo'],
    soft_skills: ['Data-driven thinking', 'User empathy', 'Iteration speed'],
    experience_fit: 61,
    domain_fit: 55,
    overall_score: 59,
    revised_resume: STUB_PDF_BASE64,
  },
  4: {
    job_id: 4,
    job_title: 'UI Engineer – Design Systems',
    job_url: 'https://example.com/jobs/4',
    company: 'Figma',
    company_url: 'https://figma.com',
    location: 'New York, NY (Hybrid)',
    posted_time: '2026-04-01',
    application_url: 'https://figma.com/jobs/apply/4',
    description:
      'Figma\'s design systems team is looking for a UI engineer to maintain and evolve our component library. You\'ll partner with designers to define token systems, write accessible components, and publish them across Figma\'s products.',
    work_type: 'Full-time',
    sector: 'Design Tools',
    technical_skills: ['React', 'TypeScript', 'CSS', 'Storybook', 'Accessibility (a11y)'],
    soft_skills: ['Design sensibility', 'Documentation', 'API design thinking'],
    experience_fit: 91,
    domain_fit: 84,
    overall_score: 89,
    revised_resume: STUB_PDF_BASE64,
  },
  5: {
    job_id: 5,
    job_title: 'Software Engineer – Growth',
    job_url: 'https://example.com/jobs/5',
    company: 'Notion',
    company_url: 'https://notion.so',
    location: 'Remote (US)',
    posted_time: '2026-03-20',
    application_url: 'https://notion.so/jobs/apply/5',
    description:
      'Notion\'s Growth team is seeking an engineer to run experiments that improve user activation and retention. You\'ll build A/B testing infrastructure, analyze results, and ship high-impact surface changes quickly.',
    work_type: 'Full-time',
    sector: 'Productivity / SaaS',
    technical_skills: ['React', 'Python', 'SQL', 'Amplitude', 'Feature flags'],
    soft_skills: ['Analytical thinking', 'Bias for action', 'Stakeholder communication'],
    experience_fit: 70,
    domain_fit: 68,
    overall_score: 70,
    revised_resume: STUB_PDF_BASE64,
  },
}

export default mockData
